export const SET_CONTEXT = 'SET_CONTEXT';
export const CLEAR_CONTEXT = 'CLEAR_CONTEXT';

export const SET_PORTAL = 'SET_PORTAL';
export const SET_VENDOR = 'SET_VENDOR';

export const SET_CURRENT_CHARITIES = 'SET_CURRENT_CHARITIES';
export const APPEND_CURRENT_CHARITIES = 'APPEND_CURRENT_CHARITIES';
export const SET_CHARITY_SEARCH_RESULTS = 'SET_CHARITY_SEARCH_RESULTS';
export const RESET_CHARITY_SEARCH_RESULTS = 'RESET_CHARITY_SEARCH_RESULTS';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_CATEGORY_CHARITIES = 'SET_CATEGORY_CHARITIES';

export const APPEND_ORDERS = 'APPEND_ORDERS';
export const SET_GIVING_HISTORY = 'SET_GIVING_HISTORY';

export const SET_TOP_CHARITIES = 'SET_TOP_CHARITIES';

