export const SET_CONTEXT = 'SET_CONTEXT';
export const CLEAR_CONTEXT = 'CLEAR_CONTEXT';

export const SET_PORTAL = 'SET_PORTAL';
export const SET_VENDOR = 'SET_VENDOR';

export const SET_SELECTION = 'SET_SELECTION';
export const SET_BLOCK_STATE = 'SET_BLOCK_STATE';
export const SET_PAGE_NAME = 'SET_PAGE_NAME';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const APPEND_CHARITIES = 'APPEND_CHARITIES';

export const FETCH_CATEGORY_CHARITIES = 'FETCH_CATEGORY_CHARITIES';

export const FETCH_CHARITY_SEARCH_RESULTS = 'CHARITY_SEARCH_RESULTS';
export const RESET_CHARITY_SEARCH_RESULTS = 'RESET_CHARITY_SEARCH_RESULTS';

export const FETCH_TOP_CHARITIES = 'FETCH_TOP_CHARITIES';

export const APPEND_ORDERS = 'APPEND_ORDERS';
export const SET_GIVING_HISTORY = 'SET_GIVING_HISTORY';

export const SET_FORM = 'SET_FORM';
export const SET_FORM_FIELD = 'SET_FORM_FIELD';
export const CLEAR_FORM = 'CLEAR_FORM';
